import Foundation

let INITIALIZE_ERROR = ": MSD must be initialized before accessing the main instance."
let EMPTY_TOKEN = "The token provided is empty"
let EMPTY_EVENT_NAME = "The event name is empty"
let MISSING_EVENT_DATA = "Missing event data"
let MISSING_RECOMMENDATION_DATA = "Missing recommendation data"
let INTERNET_UNAVAILABLE = "Internet connection unavailable"
let REQUEST_TIMEOUT = "Request timed out"
let INVALID_URL = "Invalid URL"
let UNKNOWN_ERROR = "Unknown Error"
let NO_RESPONSE = "No response received."
let UNABLE_TO_DECODE = "Unable to decode response."
let EMPTY_USER_ID = "User id is not specified"
let SERVER_UNAVAILABLE = "Our server is currently experiencing issues. Please try again later."

let BLOX_UUID = "blox_uuid"
let USER_ID = "user_id"
let URL_STRING = "url"
let PLATFORM = "platform"
let MEDIUM = "medium"
let REFERRER = "referrer"
let X_CORRELATION_ID = "x-correlation-id"
