import Foundation

let INIT_SDK_TOKEN_ERROR = "The token was not specified"
let INIT_SDK_BASE_URL_ERROR = "The base URL was not specified"
let INIT_SDK_USER_ID_ERROR = "The User id was not specified"

let TRACK_EVENT_NAME_ERROR = "An event was recorded without an event name"
let TRACK_PAGE_NAME_ERROR = "An event was recorded without a page name"

let EMPTY_TOKEN = "The token provided is empty"
let EMPTY_EVENT_NAME = "The event name is empty"
let MISSING_EVENT_DATA = "Missing event data"
let MISSING_RECOMMENDATION_DATA = "Missing recommendation data"
let INTERNET_UNAVAILABLE = "Internet connection unavailable"
let REQUEST_TIMEOUT = "Request timed out"
let INVALID_URL = "Invalid URL"
let UNKNOWN_ERROR = "Unknown Error"
let NO_RESPONSE = "No response received."
let NO_DATA = "No data received."
let UNABLE_TO_DECODE = "Unable to decode response."
let UNKNOWN = "Unknown error occurred."
let EMPTY_USER_ID = "User id is not specified"

let BLOX_UUID = "blox_uuid"
let USER_ID = "user_id"
let URL_STRING = "url"
let PLATFORM = "platform"
let MEDIUM = "medium"
let INTEGRATION_MODE = "integrationMode"
let EMBED_CODE = "embed_code"
let TIME_STAMP = "timestamp"
